the task is created
mate-academy/node_auth-app pull request #30
Opened 2024-03-07 18:35 UTC by Anastasiya145

2024-03-07 18:59 UTC, vadiimvooo requested changes
Good job. A few changes required.

2024-03-07 18:59 UTC, vadiimvooo commented on client/public/index.html
> +    -->
Remove redundant comments.

2024-03-07 18:59 UTC, vadiimvooo commented on client/public/index.html
> +    <title>React App</title>
Change title for the app

2024-03-07 18:59 UTC, vadiimvooo commented on client/public/index.html
> +    <noscript>You need to enable JavaScript to run this app.</noscript>
This can be also removed.

2024-03-07 18:59 UTC, vadiimvooo commented on client/src/pages/SignUp.tsx
> +        // .matches(/[0-9]/, 'Password must contain at least one number')
Remove comments.

2024-03-07 18:59 UTC, vadiimvooo commented on client/src/pages/SignIn.tsx
> +        // .matches(/[0-9]/, 'Password must contain at least one number')
Remove comments

2024-03-07 18:59 UTC, vadiimvooo commented on client/src/pages/ResetPassword.tsx
> +    });
This should be removed.

2024-03-07 18:59 UTC, vadiimvooo commented on client/src/pages/ResetPassword.tsx
> +          {/* <CustomTextField label="Email Address" field="email" formik={undefined} /> */}
Remove comments.

2024-03-07 18:59 UTC, vadiimvooo commented on client/src/pages/SignIn.tsx
> +      console.log(values);
Remove console.log

2024-03-07 18:59 UTC, vadiimvooo commented on client/src/pages/SignUp.tsx
> +      console.log(values);
Remove console.log

2024-03-07 18:59 UTC, vadiimvooo commented on client/src/pages/Users.tsx
> +      console.log('Error fetching users:', error);
Try to change this log for some popup like toastr.

2024-03-07 18:59 UTC, vadiimvooo commented on server/src/index.js
> +console.log(process.env.PORT);
Remove log

2024-03-07 18:59 UTC, vadiimvooo commented on server/src/routes/auth.routes.js
> +  // authMiddleware.validateEmailAndPasswordReqParams,
Remove this as well

2024-03-19 10:09 UTC, lerastarynets approved these changes
lgtm 🚀

2024-03-19 10:09 UTC, lerastarynets commented on client/src/pages/SignUp.tsx
> +        // .matches(/[0-9]/, 'Password must contain at least one number')
pls remove redundant comments

2024-04-15 09:18 UTC, Anastasiya145 reviewed
Please review my code (the last two commits)
I added the code for autogeneration of swagger doc
the API doc is here - https://app.swaggerhub.com/apis/asiva/auth-users_rest_api/1.0.0 
can you please check is doc looks correctly and good as real project? I want to add it later to my CV
thanks!

2024-08-30 14:15 UTC, closed without merging